spring:
  application:
    name: waypoint
  ai:
    model:
      chat: ${WAYPOINT_AI_CHAT_PROVIDER:ollama}
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        model: ${OPENAI_CHAT_MODEL:gpt-4o-mini}
        temperature: 0.2

---

spring:
  config:
    activate:
      on-profile: "!local"
    import: optional:configserver:https://spring.nowstart.org/config
